version: 2
jobs:
  test:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.9
      # CircleCI Mysql
      - image: circleci/mongo:latest

    working_directory: /go/src/github.com/gost-c/gost

    steps:
      - checkout

      - run:
           name: get deps
           command: |
              make install.dev

      - run:
          name: get test
          environment:
            MONGOURL: "mongodb://localhost:27017/test"
            JWTKEY: "secret test"
            ENV: prod
          command: make test
  deploy:
      machine: true
      steps:
        - checkout
        - run:
            name: push to production
            command: |
              source ci/prepare.sh
              docker info
              docker_build
              docker_push zcong/gost:latest
  staging:
    machine: true
    steps:
      - checkout
      - run:
          name: push to staging
          command: |
            source ci/prepare.sh
            docker info
            docker_build
            docker_push zcong/gost:staging

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - staging:
          context: org-global
          requires:
            - test
          filters:
            tags:
              ignore: /^v.*/
      - deploy:
          context: org-global
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
