version: 2
jobs:
  test:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.9
      # CircleCI Mysql
      - image: circleci/mongo:latest

    working_directory: /go/src/github.com/gost-c/gost

    steps:
      - checkout

      - run:
           name: get deps
           command: |
              make install.dev

      - run:
          name: get test
          environment:
            MONGOURL: "mongodb://localhost:27017/test"
            JWTKEY: "secret test"
            ENV: prod
          command: make test
  deploy:
      machine: true
      steps:
        - checkout
        - run:
            name: push to production
            command: |
              source ci/prepare.sh
              docker info
              docker_build
              docker_push zcong/gost:latest
  staging:
    machine: true
    steps:
      - checkout
      - run:
          name: push to staging
          command: |
            source ci/prepare.sh
            docker info
            docker_build
            docker_push zcong/gost:staging

  aws:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/gost-c/gost
    steps:
      - checkout
      - run:
          name: deploy to aws
          environment:
            BINDIR: /go/src/github.com/gost-c/gost/bin
          command: |
            make install.dev
            make build.up
            make install.up
            ./bin/up-gen
            ./bin/up version
            ./bin/up deploy production
            ./bin/up url

workflows:
  version: 2
  build-n-deploy:
    jobs:
#      - test:
#          filters:
#            tags:
#              only: /.*/
#      - staging:
#          context: org-global
#          requires:
#            - test
#          filters:
#            tags:
#              ignore: /^v.*/
#      - deploy:
#          context: org-global
#          requires:
#            - test
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
#      - hold:
#          type: approval
#          requires:
#            - test
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
      - aws
#          requires:
#            - hold
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
