version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8
      # CircleCI Mysql
      - image: circleci/mysql:latest
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: circle_test

    working_directory: /go/src/github.com/gost-c/gost

    steps:
      - checkout

      - run:
          name: Waiting for Mysql to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mysql && exit 1

      - run:
           name: get deps
           command: go get -t -d -v ./...

      - run:
          name: get test
          environment:
            MYSQL_DB_URL: "root:@/circle_test?charset=utf8&parseTime=True&loc=Local"
            JWT_SECRET: "secret test"
            GIN_MODE: debug
          command: go test ./...
